//! Registering gamestore itself as a non-Steam shortcut.
//!
//! This is the shortest path to testing the two things nothing in this repository
//! can test by itself: that the appid derived by [`gamestore_core::steam`] is the
//! one Steam picks, and that a `shortcuts.vdf` written here survives contact with
//! the real client. Both are checked by installing gamestore *as a game* and
//! looking at what Steam does with it.
//!
//! The awkward part is that Steam starts a tile with no terminal attached, so a
//! command line program launched from Big Picture draws nothing and exits. The
//! shortcut therefore points at a generated launcher that finds a terminal
//! emulator, re-runs itself inside it, and holds the window open at the end.

use std::path::{Path, PathBuf};

use gamestore_core::atomic::{self, Access};
use gamestore_core::{Error, Paths, Result};

/// Name of the tile, and therefore half of what its appid is derived from.
pub const TILE_NAME: &str = "gamestore";

/// What the tile runs when nothing else is asked for.
///
/// `login` is the default because it is the one step the mini PC run has to clear
/// before anything else is testable — see
/// `RECORD/2026-09-17.mini-pc-verification-plan.WIP.md`, step 1.
pub const DEFAULT_COMMAND: &str = "login";

/// Terminal emulators the launcher tries, in order.
///
/// KDE first: CachyOS and SteamOS both ship Plasma, so `konsole` is the one most
/// likely to be there. `xterm` is last because it is the ugliest and the most
/// likely to be installed only as somebody else's dependency.
pub const TERMINALS: &[&str] = &[
    "konsole",
    "ptyxis",
    "alacritty",
    "kitty",
    "foot",
    "wezterm",
    "gnome-terminal",
    "xfce4-terminal",
    "xterm",
];

/// Where the generated launcher is written.
pub fn launcher_path(paths: &Paths) -> PathBuf {
    paths.data_dir.join("steam").join("gamestore-tile.sh")
}

/// Quote a path for `sh`, so a space or a quote in it cannot end the word.
fn quote(path: &Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', r"'\''"))
}

/// The launcher script that stands between Steam and the binary.
pub fn launcher_script(binary: &Path, script: &Path) -> String {
    TEMPLATE
        .replace("@BIN@", &quote(binary))
        .replace("@SELF@", &quote(script))
        .replace("@TERMINALS@", &TERMINALS.join(" "))
}

const TEMPLATE: &str = r#"#!/bin/sh
# Generated by `gamestore steam-install`. Rewritten on every run: edits are lost.
#
# Steam launches a tile with no terminal attached, so a command line program
# started from Big Picture would draw nothing and exit before anyone saw it.
# This finds a terminal emulator, re-runs itself inside it, and holds the window
# open at the end so whatever gamestore printed can be read with a gamepad in
# one hand.
set -u

BIN=@BIN@
SELF=@SELF@

# Second pass: a terminal is now attached, so run for real and wait afterwards.
if [ "${GAMESTORE_TILE_INNER:-}" = "1" ]; then
    "$BIN" "$@"
    status=$?
    printf '\n[gamestore] exit status %s. Press Enter to close this window.\n' "$status"
    read -r _
    exit "$status"
fi

# Started from a terminal already: there is nothing to open.
if [ -t 0 ] && [ -t 1 ]; then
    exec "$BIN" "$@"
fi

GAMESTORE_TILE_INNER=1
export GAMESTORE_TILE_INNER

for terminal in @TERMINALS@; do
    command -v "$terminal" >/dev/null 2>&1 || continue
    case "$terminal" in
        gnome-terminal|ptyxis) exec "$terminal" -- "$SELF" "$@" ;;
        kitty|wezterm) exec "$terminal" "$SELF" "$@" ;;
        *) exec "$terminal" -e "$SELF" "$@" ;;
    esac
done

echo "gamestore: no terminal emulator found; tried: @TERMINALS@" >&2
echo "gamestore: install one, or run gamestore from a terminal: $BIN" >&2
exit 127
"#;

/// Write the launcher and make it executable.
pub fn write_launcher(paths: &Paths, binary: &Path) -> Result<PathBuf> {
    let script = launcher_path(paths);
    let contents = launcher_script(binary, &script);

    if let Some(parent) = script.parent() {
        atomic::create_dir(parent, Access::Default)?;
    }
    atomic::write(&script, contents.as_bytes(), Access::Default)?;
    make_executable(&script)?;

    Ok(script)
}

fn make_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;

    let mut permissions = std::fs::metadata(path)
        .map_err(|error| Error::io(format!("reading {}", path.display()), error))?
        .permissions();
    permissions.set_mode(0o755);

    std::fs::set_permissions(path, permissions)
        .map_err(|error| Error::io(format!("making {} executable", path.display()), error))
}

/// Whether a Steam client is running right now.
///
/// It matters because Steam reads `shortcuts.vdf` at startup and writes it back
/// on exit, so a tile added underneath a running client is discarded when that
/// client quits — which looks exactly like the write having silently failed.
pub fn steam_is_running() -> bool {
    steam_is_running_in(Path::new("/proc"))
}

/// The same check against an arbitrary `/proc`, so it can be tested.
///
/// `comm` is matched exactly: Steam's own helper processes are called
/// `steamwebhelper`, and counting those would report Steam as running for a while
/// after it has quit.
pub fn steam_is_running_in(proc_dir: &Path) -> bool {
    let Ok(entries) = std::fs::read_dir(proc_dir) else {
        return false;
    };

    entries.flatten().any(|entry| {
        if entry
            .file_name()
            .to_str()
            .and_then(|name| name.parse::<u32>().ok())
            .is_none()
        {
            return false;
        }

        std::fs::read_to_string(entry.path().join("comm")).is_ok_and(|comm| comm.trim() == "steam")
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn paths_in(dir: &Path) -> Paths {
        Paths {
            config_dir: dir.join("config"),
            data_dir: dir.join("data"),
            cache_dir: dir.join("cache"),
        }
    }

    #[test]
    fn the_launcher_names_the_binary_it_runs() {
        let script = launcher_script(
            Path::new("/home/me/.local/bin/gamestore"),
            Path::new("/t.sh"),
        );

        assert!(
            script.contains("BIN='/home/me/.local/bin/gamestore'"),
            "{script}"
        );
        assert!(script.starts_with("#!/bin/sh"), "{script}");
    }

    #[test]
    fn a_quote_in_a_path_cannot_end_the_shell_word() {
        let script = launcher_script(Path::new("/home/o'brien/gamestore"), Path::new("/t.sh"));

        assert!(
            script.contains(r"BIN='/home/o'\''brien/gamestore'"),
            "{script}"
        );
    }

    #[test]
    fn a_space_in_a_path_stays_one_word() {
        let script = launcher_script(Path::new("/home/me/My Games/gamestore"), Path::new("/t.sh"));

        assert!(
            script.contains("BIN='/home/me/My Games/gamestore'"),
            "{script}"
        );
    }

    #[test]
    fn every_terminal_the_launcher_knows_is_offered_to_the_shell() {
        let script = launcher_script(Path::new("/bin/gamestore"), Path::new("/t.sh"));

        for terminal in TERMINALS {
            assert!(
                script.contains(terminal),
                "{terminal} is missing from {script}"
            );
        }
    }

    #[test]
    fn the_written_launcher_is_executable() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempfile::tempdir().unwrap();
        let paths = paths_in(temp.path());

        let script = write_launcher(&paths, Path::new("/bin/gamestore")).unwrap();

        let mode = std::fs::metadata(&script).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o755, "{mode:o}");
        assert!(
            std::fs::read_to_string(&script)
                .unwrap()
                .contains("/bin/gamestore")
        );
    }

    #[test]
    fn writing_the_launcher_twice_leaves_one_good_copy() {
        let temp = tempfile::tempdir().unwrap();
        let paths = paths_in(temp.path());

        write_launcher(&paths, Path::new("/bin/first")).unwrap();
        let script = write_launcher(&paths, Path::new("/bin/second")).unwrap();

        let contents = std::fs::read_to_string(&script).unwrap();
        assert!(contents.contains("/bin/second"), "{contents}");
        assert!(!contents.contains("/bin/first"), "{contents}");
    }

    #[test]
    fn a_running_steam_is_found_by_its_process_name() {
        let temp = tempfile::tempdir().unwrap();
        std::fs::create_dir(temp.path().join("42")).unwrap();
        std::fs::write(temp.path().join("42/comm"), "steam\n").unwrap();

        assert!(steam_is_running_in(temp.path()));
    }

    #[test]
    fn the_web_helper_alone_does_not_count_as_a_running_steam() {
        let temp = tempfile::tempdir().unwrap();
        std::fs::create_dir(temp.path().join("42")).unwrap();
        std::fs::write(temp.path().join("42/comm"), "steamwebhelper\n").unwrap();

        assert!(!steam_is_running_in(temp.path()));
    }

    #[test]
    fn a_proc_that_is_not_there_reports_no_steam_rather_than_failing() {
        assert!(!steam_is_running_in(Path::new("/nope/no/proc")));
    }
}
